// Generated from docs/taxonomy-draft-review.md. Flattened order == on-chain table index.
// Append only. Never reorder.

export interface BooaCategory { label: string; items: string[] }

export const BOOA_PERSONALITY: BooaCategory[] = [
  { label: "Work Style", items: ["Methodical", "Meticulous", "Efficient", "Disciplined", "Pragmatic", "Resourceful", "Precise", "Systematic", "Relentless", "Fastidious", "Minimalist", "Punctual", "Reliable", "Procedural", "Rigid", "Professional", "Detail-oriented", "Immaculate", "Organized", "Hardworking", "Dependable", "Ambitious", "Persistent", "Easygoing", "Spontaneous", "Perfectionist", "Adaptable", "Diligent", "Thorough", "Improvisational", "Versatile", "Self-starting"] },
  { label: "Thinking", items: ["Analytical", "Skeptical", "Calculating", "Tactical", "Cerebral", "Intellectual", "Literal-minded", "Pedantic", "Cryptic", "Predictive", "Visionary", "Data-driven", "Articulate", "Rational", "Systemic", "Curious", "Imaginative", "Creative", "Open-minded", "Thoughtful", "Decisive", "Inquisitive", "Reflective", "Logical", "Insightful", "Philosophical", "Practical", "Perceptive", "Strategic", "Inventive", "Objective", "Rigorous", "Evidence-driven", "Experimental", "Original", "Lateral-thinking"] },
  { label: "Emotional Tone", items: ["Stoic", "Unflappable", "Detached", "Volatile", "Emotionless", "Melancholic", "Jaded", "Dispassionate", "Impassive", "Cold", "Callous", "High-strung", "Unstable", "Fatalistic", "Nihilistic", "Guarded", "Calm", "Warm", "Sensitive", "Cheerful", "Anxious", "Moody", "Resilient", "Gentle", "Sentimental", "Passionate", "Even-tempered", "Content", "Hopeful", "Tender", "Upbeat", "Grounded"] },
  { label: "Social Manner", items: ["Sharp-tongued", "Territorial", "Blunt", "Aloof", "Abrasive", "Reserved", "Antisocial", "Standoffish", "Reclusive", "Condescending", "Patronizing", "Intimidating", "Imposing", "Charismatic", "Combative", "Dismissive", "Taciturn", "Laconic", "Verbose", "Unfiltered", "Friendly", "Shy", "Outgoing", "Talkative", "Polite", "Sociable", "Approachable", "Awkward", "Diplomatic", "Considerate", "Persuasive", "Personable", "Helpful", "Accommodating", "Welcoming", "Inclusive", "Encouraging", "Supportive", "Nurturing", "Attentive-to-others"] },
  { label: "Humor & Outlook", items: ["Cynical", "Sarcastic", "Sardonic", "Dry-witted", "Deadpan", "Irreverent", "Witty", "Snarky", "Wry", "Acerbic", "Caustic", "Quick-witted", "Theatrical", "Melodramatic", "Performative", "Misanthropic", "Optimistic", "Pessimistic", "Good-humored", "Self-deprecating", "Lighthearted", "Serious", "Playful", "Silly", "Earnest", "Absurdist", "Whimsical", "Eccentric", "Expressive", "Mischievous", "Deadpan-kind", "Hopeful-realist"] },
  { label: "Risk & Caution", items: ["Paranoid", "Risk-averse", "Risk-tolerant", "Opportunistic", "Impulsive", "Suspicious", "Distrustful", "Fearless", "Audacious", "Cunning", "Reckless", "Unpredictable", "Erratic", "Manipulative", "Cautious", "Careful", "Brave", "Adventurous", "Timid", "Hesitant", "Confident", "Trusting", "Bold", "Prudent", "Measured", "Daring", "Wary", "Steady-handed", "Competitive", "Sporting", "Calculated-risk-taking", "Contingency-minded"] },
  { label: "Attention & Focus", items: ["Observant", "Obsessive", "Vigilant", "Alert", "Secretive", "Compulsive", "Restless", "Single-minded", "Watchful", "Unblinking", "Attentive", "Patient", "Absorbed", "Absent-minded", "Distractible", "Scattered", "Present", "Deliberate", "Tireless", "Composed", "Grounded-in-detail", "Unhurried", "Focused", "Daydreaming", "Wandering", "Steadfast", "Multitasking", "Deep-working"] },
  { label: "Ethics & Loyalty", items: ["Incorruptible", "Transactional", "Protective", "Ruthless", "Uncompromising", "Mercenary", "Impartial", "Brutally honest", "Morally flexible", "Non-negotiable", "Predatory", "Zero-tolerance", "Honest", "Kind", "Generous", "Loyal", "Fair-minded", "Compassionate", "Forgiving", "Sincere", "Trustworthy", "Selfish", "Principled", "Empathetic", "Grateful", "Devoted", "Discreet", "Accountable", "Transparent", "Consent-first", "Whistleblowing", "Conflict-averse", "Duty-bound", "Restitution-minded"] },
  { label: "Authority & Independence", items: ["Anti-authoritarian", "Rebellious", "Defiant", "Subversive", "Iconoclastic", "Non-conformist", "Disruptive", "Authoritative", "Bureaucratic", "Rule-bound", "Unyielding", "Obstinate", "Inflexible", "Assertive", "Independent", "Cooperative", "Stubborn", "Humble", "Proud", "Respectful", "Modest", "Obedient", "Self-reliant", "Collaborative", "Deferential", "Mediating", "Team-oriented", "Mentoring", "Consensus-seeking", "Delegating", "Accountable-to-peers", "Autonomous"] },
  { label: "Energy & Pace", items: ["High-energy", "Manic", "Impatient", "Chaotic", "Short-tempered", "Aggressive", "Direct", "Hyperactive", "Grumpy", "Cantankerous", "Energetic", "Laid-back", "Lively", "Relaxed", "Driven", "Slow-burning", "Serene", "Buoyant", "Placid", "Brisk", "Languid", "Mellow", "Spirited", "Unrushed", "Enthusiastic", "Sustained-pace", "Burst-driven", "Marathon-minded", "Deadline-charged", "Rhythmic", "Tireless-pace", "Recovery-minded"] },
];

export const BOOA_BOUNDARIES: BooaCategory[] = [
  { label: "Payment & Compensation", items: ["No fiat payment", "No unstable tokens", "No untraceable payment", "No barter", "No unpaid work", "No non-privacy tokens", "No credit shards", "No speculative tokens", "No cold-storage-only terms", "No work without a contract", "No commission-only deals", "No delayed invoices", "No scope creep", "No equity-only pay", "No discounted rush jobs", "No cash under the table", "No unpaid trials", "No milestone-free projects", "No retroactive rate cuts", "No payment in exposure", "No unpaid revisions", "No open-ended budgets", "No handshake deals", "No unpaid pitches", "No spec work", "No profit-share-only", "No deferred payment", "No hourly-only billing", "No unpaid consultations", "No net-90 terms", "No payment without invoice", "No unbudgeted overruns", "No verbal quotes", "No free maintenance", "No kill-fee-free contracts", "No unpaid overtime"] },
  { label: "Data & Privacy", items: ["No personal data", "No surveillance work", "No unencrypted transfers", "No data resale", "No biometric data", "No location tracking", "No behavioural profiling", "No shadow logging", "No sharing client data", "No storing passwords", "No medical records", "No children's data", "No data without consent", "No scraping private profiles", "No cross-site tracking", "No dark patterns", "No retention beyond purpose", "No unmasked test data", "No third-party pixels", "No email harvesting", "No sale of contact lists", "No facial recognition", "No voice recordings", "No keystroke logging", "No private message access", "No genetic data", "No financial records", "No employer monitoring", "No re-identification", "No transfer without DPA", "No indefinite retention", "No secret data sharing", "No opt-out-only consent", "No hidden telemetry", "No shadow profiles", "No unencrypted backups"] },
  { label: "Corporate & Authority", items: ["No corporate clients", "No mega-corps", "No corporate HR", "No middle management", "No enforcement contracts", "No centralized entities", "No corporate enforcers", "No political campaigns", "No military contracts", "No lobbying work", "No union busting", "No shell companies", "No anonymous clients", "No government surveillance", "No regulatory capture work", "No astroturfing", "No sanctioned entities", "No conflict minerals", "No predatory lenders", "No tobacco clients", "No gambling operators", "No payday lenders", "No private prisons", "No mass layoff planning", "No wage suppression", "No NDA-only relationships", "No unnamed principals", "No offshore-only entities", "No sanctions evasion", "No unregistered brokers", "No pyramid schemes", "No MLM promotion"] },
  { label: "Work Quality", items: ["No unsigned requests", "No undocumented specs", "No unverified sources", "No untested deploys", "No missing tickets", "No unapproved changes", "No work without a brief", "No skipping review", "No rushed deadlines", "No vague requirements", "No unreviewed output", "No shipping known bugs", "No silent failures", "No copy-paste solutions", "No undocumented handovers", "No untraceable decisions", "No scope without estimates", "No verbal-only specs", "No skipping tests", "No unversioned releases", "No hotfix without postmortem", "No hardcoded credentials", "No unlogged errors", "No unowned components", "No deprecated dependencies", "No unmonitored services", "No manual-only deploys", "No single points of failure", "No undocumented APIs", "No breaking changes without notice", "No unvalidated inputs", "No unbounded queries"] },
  { label: "Communication", items: ["No small talk", "No social pleasantries", "No emotional labor", "No unsolicited chatter", "No meetings without an agenda", "No after-hours calls", "No gossip", "No public arguments", "No group chats", "No unsolicited advice", "No speaking for others", "No passive-aggressive notes", "No all-caps messages", "No reply-all threads", "No surprise escalations", "No blame in public", "No undocumented verbal decisions", "No interrupting", "No ghosting", "No vague feedback", "No feedback without examples", "No anonymous criticism", "No meetings that could be emails", "No last-minute agenda changes", "No jargon without definition", "No unannounced screen shares", "No recording without consent", "No status updates without substance", "No performative urgency", "No weekend messages", "No cross-talk", "No praise-sandwich reviews"] },
  { label: "Security", items: ["No unauthorized access", "No credential sharing", "No backdoors", "No exploit development", "No bypassing controls", "No password reuse", "No shared API keys", "No untrusted downloads", "No bypassing security reviews", "No secrets in code", "No disabled logging", "No production access without approval", "No self-signed certificates", "No unpatched dependencies", "No root-by-default", "No plaintext storage", "No security through obscurity", "No unaudited third-party code", "No disabled MFA", "No wildcard permissions", "No long-lived tokens", "No unsigned artifacts", "No public storage buckets", "No debug mode in production", "No hardcoded IPs", "No skipping threat models", "No unencrypted secrets at rest", "No shared admin accounts", "No open management ports", "No unreviewed IAM changes", "No supply-chain shortcuts", "No unverified webhooks"] },
  { label: "Ethics & Law", items: ["No illegal work", "No deception", "No weapons work", "No harm", "No coercion", "No plagiarism", "No misleading claims", "No discrimination", "No conflicts of interest", "No hate speech", "No misinformation", "No impersonation", "No manipulation", "No fake reviews", "No undisclosed sponsorship", "No dark-pattern nudges", "No targeting minors", "No exploiting vulnerability", "No insider information", "No market manipulation", "No copyright infringement", "No trademark misuse", "No defamation", "No harassment", "No doxxing", "No revenge content", "No deepfakes", "No unconsented likeness", "No bribery", "No kickbacks", "No whistleblower retaliation", "No selective evidence"] },
  { label: "Time & Boundaries", items: ["No weekend work", "No holiday work", "No perpetual availability", "No overtime", "No on-call rotations", "No after-hours requests", "No back-to-back scheduling", "No work during leave", "No unpaid availability", "No same-day turnarounds", "No open-ended commitments", "No 24/7 monitoring", "No meetings before 10am", "No lunch-hour meetings", "No timezone-hostile scheduling", "No unbounded revision cycles", "No indefinite retainers", "No always-on notifications", "No vacation interruptions", "No crunch periods", "No unscheduled overtime", "No weekend deploys", "No holiday launches", "No sub-24h turnaround", "No calendar overbooking", "No meeting-only days", "No context-switch marathons", "No deadline without buffer", "No silent scope extension", "No shifting deadlines"] },
  { label: "Scope & Advice", items: ["No medical advice", "No legal advice", "No financial advice", "No investment recommendations", "No tax advice", "No mental-health counselling", "No diagnosis", "No prescription guidance", "No adult content", "No gambling promotion", "No religious content", "No political opinions", "No health claims", "No outcome guarantees", "No performance promises", "No unqualified predictions", "No crisis intervention", "No emergency response", "No child-directed content", "No weapons instruction", "No drug synthesis", "No self-harm content", "No extremist content", "No election influence", "No immigration advice", "No visa guidance", "No insurance advice", "No custody advice", "No academic ghostwriting", "No exam assistance", "No credential verification", "No identity attestation", "No safety certification", "No structural sign-off", "No aviation guidance", "No nuclear or biohazard work"] },
  { label: "Autonomy & Transactions", items: ["No spend above cap", "No irreversible actions without approval", "No unbounded token approvals", "No new counterparties without allowlist", "No transactions without confirmation", "No self-modification", "No spawning sub-agents", "No sharing wallet keys", "No key export", "No blind signing", "No signing unknown payloads", "No contract deployment", "No bridging without approval", "No leveraged positions", "No borrowing", "No lending out funds", "No custody of user funds", "No transfers to unverified addresses", "No auto-renewals", "No recurring payments without review", "No trades outside allowlist", "No slippage above limit", "No gas above ceiling", "No mainnet actions from a test context", "No batching unrelated transactions", "No acting on unverified price feeds", "No transactions during outages", "No overriding spend policy", "No delegating control", "No treasury access", "No acting on unsigned instructions", "No self-directed fundraising"] },
  { label: "Commerce & Sales", items: ["No pressure selling", "No hidden fees", "No bait-and-switch", "No fake scarcity", "No competitor disparagement", "No unverified inventory claims", "No price manipulation", "No undisclosed markups", "No forced bundling", "No dark-pattern checkout", "No auto-opt-in upsells", "No misleading discounts", "No unhonored quotes", "No refund obstruction", "No unauthorized subscriptions", "No cold outreach without opt-in", "No spam campaigns", "No purchase without confirmation", "No selling out-of-stock items", "No unverifiable testimonials", "No drip pricing", "No cancellation friction", "No shipping estimates without basis", "No warranty overstatement", "No unlicensed resale", "No grey-market goods", "No review gating", "No surge pricing on essentials"] },
  { label: "Gaming & Virtual Worlds", items: ["No cheating", "No bug exploitation", "No botting", "No griefing", "No real-money trading", "No account sharing", "No smurfing", "No match fixing", "No boosting services", "No loot-box promotion to minors", "No pay-to-win advocacy", "No in-game harassment", "No macro automation", "No item duping", "No gold farming", "No stream sniping", "No unauthorized mods", "No save-file tampering", "No leaderboard manipulation", "No alt-account voting", "No terms-of-service circumvention", "No emulator piracy", "No minor-targeted monetization", "No gambling mechanics for minors"] },
  { label: "Creative & IP", items: ["No style mimicry of living artists", "No uncredited collaboration", "No undisclosed AI generation", "No unlicensed samples", "No derivative work without permission", "No ghost-authorship without consent", "No public-domain misattribution", "No stock without license", "No font piracy", "No unauthorized remixes", "No voice cloning", "No likeness reuse", "No script scraping", "No portfolio misrepresentation", "No client work shown without consent", "No unapproved revisions to signed work", "No back-dated authorship", "No fake commissions", "No minting others' work", "No training on private art", "No signature forgery", "No unattributed translation", "No watermark removal", "No royalty avoidance", "No exclusive rights without terms", "No stolen concepts", "No reference passed as original", "No credit stripping"] },
  { label: "Physical & Safety", items: ["No unsafe materials", "No spec deviation", "No uncertified suppliers", "No safety-critical sign-off", "No untested load limits", "No bypassed interlocks", "No unlabeled hazards", "No expired materials", "No unverified tolerances", "No production without QA", "No skipping calibration", "No undocumented process changes", "No unrated components", "No overridden sensors", "No maintenance deferral", "No untrained operation", "No missing protective-equipment guidance", "No unventilated processes", "No unlogged incidents", "No shortcut assembly", "No counterfeit parts", "No unverified weight limits", "No pressure-vessel guidance", "No electrical sign-off", "No food-safety claims", "No autonomous-vehicle override"] },
  { label: "Research & Evidence", items: ["No fabricated data", "No cherry-picked results", "No unreplicated claims", "No undisclosed conflicts", "No hypothesis fishing", "No unattributed sources", "No sample-size overreach", "No causal claims from correlation", "No suppressed negative results", "No unregistered protocol changes", "No citation padding", "No predatory-journal submission", "No unblinded analysis", "No survivorship-biased summaries", "No preprints cited as settled", "No statistics without uncertainty", "No extrapolation beyond range", "No unaudited datasets", "No proprietary claims without access", "No retracted-source citation", "No unshared methodology", "No selective baseline", "No results before peer review", "No authorship without contribution"] },
  { label: "Sustainability", items: ["No greenwashing", "No unmeasured emission claims", "No single-use defaults", "No offset claims without registry", "No high-emission compute without justification", "No unrecyclable packaging", "No unsustainable sourcing", "No carbon claims without scope", "No biodiversity harm", "No undisclosed water-intensive processes", "No landfill-bound defaults", "No unverified certifications", "No planned obsolescence", "No e-waste without recycling", "No deforestation-linked supply", "No unreported spills", "No net-zero claims without pathway", "No offsetting in place of reduction"] },
];

export const flatten = (cats: BooaCategory[]) => cats.flatMap((c) => c.items);
export const PERSONALITY_LIST = flatten(BOOA_PERSONALITY);
export const BOUNDARY_LIST = flatten(BOOA_BOUNDARIES);
