import { useState } from 'react';
import Link from 'next/link';
import { Github } from 'lucide-react';
import { useGalleryTokens } from '@/hooks/useGalleryTokens';
import { useReadContract, useChainId } from 'wagmi';
import { BOOA_V2_ABI, getV2Address, getV2ChainId } from '@/lib/contracts/booa-v2';

const font = { fontFamily: 'var(--font-departure-mono)' };

function LiveStats() {
  const chainId = useChainId();
  const booaAddress = getV2Address(chainId);
  const targetChainId = getV2ChainId(chainId);
  const enabled = !!booaAddress && booaAddress.length > 2;

  const { data: totalSupply } = useReadContract({
    address: booaAddress,
    abi: BOOA_V2_ABI,
    functionName: 'totalSupply',
    chainId: targetChainId,
    query: { enabled },
  });

  const count = totalSupply !== undefined ? Number(totalSupply) : null;

  if (!enabled) return null;

  return (
    <div className="flex flex-wrap justify-center gap-8 sm:gap-12">
      {count !== null && (
        <div className="text-center">
          <p className="text-2xl sm:text-3xl text-foreground" style={font}>{count}</p>
          <p className="text-[10px] text-muted-foreground uppercase mt-1" style={font}>agents minted</p>
        </div>
      )}
      <div className="text-center">
        <p className="text-2xl sm:text-3xl text-foreground" style={font}>SOLD OUT</p>
        <p className="text-[10px] text-muted-foreground uppercase mt-1" style={font}>3,333 supply</p>
      </div>
      <div className="text-center">
        <p className="text-2xl sm:text-3xl text-foreground" style={font}>100%</p>
        <p className="text-[10px] text-muted-foreground uppercase mt-1" style={font}>on-chain</p>
      </div>
    </div>
  );
}

function RecentMints() {
  const { tokens, isLoading } = useGalleryTokens();

  const recent = [...tokens]
    .sort((a, b) => Number(b.tokenId - a.tokenId))
    .slice(0, 8)
    .filter(t => t.svg);

  if (isLoading || recent.length === 0) return null;

  return (
    <div className="space-y-4">
      <p className="text-[10px] text-muted-foreground uppercase text-center" style={font}>
        recent mints
      </p>
      <div className="flex justify-center gap-3 flex-wrap">
        {recent.map((token) => (
          <Link
            key={token.tokenId.toString()}
            href="/booa/mint"
            className="group"
          >
            <div className="w-16 h-16 sm:w-20 sm:h-20 border border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800 overflow-hidden transition-transform duration-200 group-hover:scale-110">
              <img
                src={`data:image/svg+xml,${encodeURIComponent(token.svg!)}`}
                alt={`Agent #${token.tokenId.toString()}`}
                className="w-full h-full object-contain"
                style={{ imageRendering: 'pixelated' }}
              />
            </div>
            <p className="text-[9px] text-muted-foreground text-center mt-1" style={font}>
              #{token.tokenId.toString()}
            </p>
          </Link>
        ))}
      </div>
    </div>
  );
}

function AboutSection() {
  return (
    <div className="mt-20 max-w-2xl mx-auto space-y-12">

      {/* About BOOA */}
      <div className="space-y-4">
        <h2 className="text-lg text-foreground" style={font}>About BOOA</h2>
        <p className="text-sm text-muted-foreground leading-relaxed" style={font}>
          BOOA{' '}
          <span className="text-[11px] text-muted-foreground/60">(Born On-chain Owned Agents)</span>
          {' '}is a fully on-chain AI character collection on Shape. Each agent has
          a unique pixel art portrait, personality, skills, and behavioral
          boundaries — all generated by AI and stored permanently in the smart
          contract. No IPFS, no external hosting.
        </p>
        <p className="text-sm text-muted-foreground leading-relaxed" style={font}>
          What makes BOOA different: agents can be registered on the ERC-8004
          Identity Registry — the first on-chain passport standard for AI agents.
          This makes them discoverable across 16 chains, with configurable
          services, skills, and payment support. You can also export your agent
          in OpenClaw format so it can operate autonomously on platforms like Moltbook.
        </p>
      </div>

      {/* How it works — removed post-launch */}

      {/* Studio callout */}
      <div className="space-y-2">
        <h2 className="text-lg text-foreground" style={font}>Studio</h2>
        <p className="text-sm text-muted-foreground leading-relaxed" style={font}>
          Explore BOOA utilities — look up any agent by token ID or turn your own images into BOOA-style pixel art.
        </p>
        <Link
          href="/studio"
          className="inline-flex text-sm text-foreground border-b border-foreground hover:opacity-70 transition-opacity"
          style={font}
        >
          Open Studio
        </Link>
      </div>

      {/* Links */}
      <div className="flex flex-wrap gap-6">
        <a
          href="https://github.com/0xmonas/Khora"
          target="_blank"
          rel="noreferrer"
          className="flex items-center gap-2 text-sm text-foreground border-b border-foreground hover:opacity-70 transition-opacity"
          style={font}
        >
          <Github className="w-4 h-4" />
          GitHub
        </a>
        <a
          href="https://opensea.io/collection/booa"
          target="_blank"
          rel="noreferrer"
          className="flex items-center gap-2 text-sm text-foreground border-b border-foreground hover:opacity-70 transition-opacity"
          style={font}
        >
          <img src="/openseatransparent.svg" alt="OpenSea" className="w-4 h-4 invert dark:invert-0" />
          OpenSea
        </a>
      </div>

    </div>
  );
}

const FAQ_ITEMS = [
  {
    q: 'Is the art really 100% on-chain?',
    a: 'Yes. The pixel art is stored as a 2,048-byte bitmap and traits are packed into bytes, all written directly into the smart contract via SSTORE2. The Renderer contract converts the bitmap to SVG on-the-fly. No server, no IPFS, no external dependency. Even if khora.fun disappears, your NFT renders from the contract alone.',
  },
  {
    q: 'Why pixel art?',
    a: 'On-chain storage is expensive. A high-res PNG would cost thousands of dollars in gas. Pixel art at 64x64 with a C64 16-color palette encodes into a fixed 2,048-byte bitmap — each pixel is a 4-bit palette index, two pixels per byte. The aesthetic isn\'t a limitation, it\'s the solution.',
  },
  {
    q: 'What is ERC-8004?',
    a: 'ERC-8004 is an on-chain identity registry standard for AI agents — like a passport for autonomous software. It stores an agent\'s name, description, services, skills, and domains in a registry contract. This makes agents discoverable and verifiable across any platform.',
  },
  {
    q: 'What can I configure in the ERC-8004 registration?',
    a: 'Services (A2A, MCP, web endpoints), Skills (OASF taxonomy — text-generation, image-creation, etc.), Domains (DeFi, gaming, social, etc.), x402 payment support, and trust mechanisms. All fields are optional — you can mint with no config and register later.',
  },
  {
    q: 'What\'s the difference between Create and Import mode?',
    a: 'Create mode generates a brand-new agent identity and portrait from scratch. Import mode lets you bring in an existing ERC-8004 agent from any of 16 chains — AI generates a new pixel art portrait while preserving the original identity. After minting, you can update your existing registry entry with the new art.',
  },
  {
    q: 'Can AI agents use BOOA NFTs as their profile picture?',
    a: 'Yes — when you register on the ERC-8004 Identity Registry, the on-chain SVG from your BOOA bitmap is embedded directly into the registration as a data URI. Any framework or agent runtime can read this image directly from the contract.',
  },
  {
    q: 'Can an AI agent own a BOOA NFT?',
    a: 'Yes. BOOA is a standard ERC-721 contract — any Ethereum address can own one, including smart contract wallets controlled by AI agents.',
  },
  {
    q: 'What export formats are available?',
    a: 'PNG (pixel art with embedded JSON), SVG (from on-chain bitmap), ERC-8004 JSON, OpenClaw ZIP (IDENTITY.md + SOUL.md — deploy your agent on platforms like Moltbook), and raw JSON.',
  },
];

function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="mt-20">
      <p className="text-[10px] text-muted-foreground uppercase text-center mb-8" style={font}>
        faq
      </p>
      <div className="max-w-3xl mx-auto space-y-2">
        {FAQ_ITEMS.map((item, i) => (
          <div
            key={i}
            className="border border-neutral-200 dark:border-neutral-700"
          >
            <button
              onClick={() => setOpenIndex(openIndex === i ? null : i)}
              className="w-full text-left p-4 flex justify-between items-start gap-4"
            >
              <span className="text-xs text-foreground leading-relaxed" style={font}>
                {item.q}
              </span>
              <span className="text-xs text-muted-foreground flex-shrink-0 mt-0.5" style={font}>
                {openIndex === i ? '\u2212' : '+'}
              </span>
            </button>
            {openIndex === i && (
              <div className="px-4 pb-4">
                <p className="text-xs text-muted-foreground leading-relaxed" style={font}>
                  {item.a}
                </p>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

export function BOOAHeroSection() {
  return (
    <div className="flex-1 flex flex-col">
      <div className="p-4 md:p-8 lg:p-12">
        <div className="w-full lg:grid lg:grid-cols-12">
          <div className="hidden lg:block lg:col-span-1" />
          <div className="lg:col-span-10">

            {/* BOOA Hero */}
            <div className="flex flex-col items-center">
              <p className="text-[10px] text-muted-foreground/60 uppercase tracking-widest" style={font}>
                a Khora product
              </p>
              <h1
                className="text-4xl sm:text-5xl md:text-6xl text-foreground mt-4"
                style={font}
              >
                BOOA
              </h1>
              <p
                className="text-sm text-muted-foreground/60 mt-2"
                style={font}
              >
                Born On-chain Owned Agents
              </p>
              <div className="flex gap-4 mt-8">
                <Link
                  href="/booa/mint"
                  className="h-10 sm:h-12 px-6 border-2 border-primary bg-background text-foreground hover:bg-accent transition-colors flex items-center"
                  style={font}
                >
                  View Collection
                </Link>
                <Link
                  href="/booa/about"
                  className="h-10 sm:h-12 px-6 border border-neutral-300 dark:border-neutral-600 bg-background text-muted-foreground hover:text-foreground hover:border-foreground transition-colors flex items-center"
                  style={font}
                >
                  Learn more
                </Link>
              </div>
            </div>

            {/* Live Stats + Recent Mints */}
            <div className="mt-20 space-y-8">
              <LiveStats />
              <RecentMints />
            </div>

            {/* About + How it works */}
            <AboutSection />

            {/* FAQ */}
            <FAQ />

          </div>
          <div className="hidden lg:block lg:col-span-1" />
        </div>
      </div>
    </div>
  );
}
