'use client';

import { useState, useEffect, useCallback } from 'react';
import { useChainId, useSwitchChain, useWriteContract, useConfig, usePublicClient } from 'wagmi';
import { getPublicClient } from '@wagmi/core';
import { AlertTriangle, Check } from 'lucide-react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogClose,
} from '@/components/ui/dialog';
import { BOOA_ADAPTER_ABI } from '@/lib/contracts/booa-adapter';
import { getRegistryAddress } from '@/lib/contracts/identity-registry';
import {
  decodeAgentWalletBlob,
  checkAgentWalletBlobSignature,
  type AgentWalletBlob,
} from '@/lib/contracts/agent-wallet';
import { friendlyError } from '@/utils/helpers/friendlyError';
import { CHAIN_CONFIG } from '@/types/agent';

const font = { fontFamily: 'var(--font-departure-mono)' };

function chainName(chainId: number): string {
  return Object.values(CHAIN_CONFIG).find((c) => c.chainId === chainId)?.name || `chain ${chainId}`;
}

interface Preview {
  blob: AgentWalletBlob;
  sigState: 'ok' | 'unrecoverable';
}

/**
 * Self-contained agent-wallet linker. Mirrors the audited Bridge flow byte-for-byte:
 * decode → chainId/agentId/deadline (≤ now+300) validation → local EIP-712 signature
 * recovery → SHOW the wallet address → confirm → adapter.setAgentWallet. The first arg
 * to setAgentWallet is the ERC-8004 `agentId`, NOT the BOOA tokenId.
 */
export function LinkAgentWalletModal({
  open, onClose, agentId, chainId, adapterAddress, currentWallet, onLinked,
}: {
  open: boolean;
  onClose: () => void;
  agentId: number;
  chainId: number;
  adapterAddress: `0x${string}`;
  currentWallet: string | null;
  onLinked: (wallet: string) => void;
}) {
  const walletChainId = useChainId();
  const { switchChainAsync } = useSwitchChain();
  const { writeContractAsync } = useWriteContract();
  const wagmiConfig = useConfig();
  const publicClient = usePublicClient({ chainId });

  const [code, setCode] = useState('');
  const [preview, setPreview] = useState<Preview | null>(null);
  const [status, setStatus] = useState<'idle' | 'linking' | 'success' | 'error'>('idle');
  const [error, setError] = useState<string | null>(null);
  const [acknowledged, setAcknowledged] = useState(false);
  const [secondsLeft, setSecondsLeft] = useState(0);

  const reset = useCallback(() => {
    setCode(''); setPreview(null); setStatus('idle'); setError(null); setAcknowledged(false);
  }, []);

  useEffect(() => { if (open) reset(); }, [open, reset]);

  const deadline = preview ? Number(preview.blob.deadline) : 0;
  useEffect(() => {
    if (!preview) return;
    const tick = () => setSecondsLeft(Math.max(0, deadline - Math.floor(Date.now() / 1000)));
    tick();
    const iv = setInterval(tick, 1000);
    return () => clearInterval(iv);
  }, [preview, deadline]);

  const prepare = useCallback(async () => {
    setPreview(null);
    setError(null);
    const blob = decodeAgentWalletBlob(code.trim());
    if (!blob) { setError('Invalid link code. Copy it exactly from your runtime.'); return; }
    if (blob.chainId !== chainId) { setError(`This link is for a different chain (id ${blob.chainId}).`); return; }
    if (blob.agentId !== String(agentId)) { setError(`This link is for agent #${blob.agentId}, not #${agentId}.`); return; }
    const nowSec = Math.floor(Date.now() / 1000);
    if (Number(blob.deadline) < nowSec) { setError('This link has expired. Generate a fresh one (valid ~4 minutes).'); return; }
    if (Number(blob.deadline) > nowSec + 300) {
      setError('This link was generated by an outdated runtime (deadline beyond the registry’s 5-minute cap). Update the template and generate a fresh link.');
      return;
    }
    const sigState = await checkAgentWalletBlobSignature(blob, getRegistryAddress(chainId), adapterAddress);
    if (sigState === 'mismatch') {
      setError('This link code is not signed by the wallet it asks to bind. Do not use it.');
      return;
    }
    setPreview({ blob, sigState });
  }, [code, chainId, agentId, adapterAddress]);

  const confirm = useCallback(async () => {
    if (!preview) return;
    const { blob } = preview;
    const nowSec = Math.floor(Date.now() / 1000);
    if (Number(blob.deadline) < nowSec) {
      setPreview(null); setStatus('error'); setError('This link expired while it was open. Generate a fresh one.');
      return;
    }
    try {
      setError(null); setStatus('linking');
      if (walletChainId !== chainId) await switchChainAsync({ chainId });
      const hash = await writeContractAsync({
        address: adapterAddress,
        chainId,
        abi: BOOA_ADAPTER_ABI,
        functionName: 'setAgentWallet',
        args: [BigInt(agentId), blob.wallet, BigInt(blob.deadline), blob.signature],
      });
      const client = getPublicClient(wagmiConfig, { chainId }) || publicClient;
      if (client) await client.waitForTransactionReceipt({ hash });
      setStatus('success');
      onLinked(blob.wallet.toLowerCase());
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Linking failed';
      if (msg.includes('User rejected') || msg.includes('user rejected') || msg.includes('denied')) {
        setStatus('idle');
        return;
      }
      setError(friendlyError(msg));
      setStatus('error');
    }
  }, [preview, walletChainId, chainId, switchChainAsync, writeContractAsync, agentId, adapterAddress, wagmiConfig, publicClient, onLinked]);

  const expired = preview ? secondsLeft <= 0 : false;
  const needsAck = preview?.sigState === 'unrecoverable';
  const canConfirm = !!preview && status !== 'linking' && !expired && (!needsAck || acknowledged);

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) onClose(); }}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle style={font} className="text-xs">
            {currentWallet ? 'Change' : 'Link'} agent wallet · #{agentId}
          </DialogTitle>
          <DialogClose className="text-muted-foreground hover:text-foreground" />
        </DialogHeader>

        <div className="p-4">
        {status === 'success' ? (
          <div className="flex flex-col items-center gap-3 py-4 text-center">
            <div className="w-10 h-10 rounded-full bg-green-600 text-white flex items-center justify-center">
              <Check className="w-5 h-5" />
            </div>
            <p className="text-sm text-foreground" style={font}>Agent wallet set onchain.</p>
            <button onClick={onClose} className="text-[11px] px-4 py-2 rounded-md bg-neutral-900 dark:bg-neutral-100 text-white dark:text-black uppercase tracking-wider" style={font}>Done</button>
          </div>
        ) : !preview ? (
          <div className="space-y-4">
            <p className="text-[11px] text-muted-foreground leading-relaxed" style={font}>
              Paste the link code your agent generates (Hermes dashboard or “link my wallet” in chat).
              The address it binds is shown for you to confirm on the next step.
            </p>
            {currentWallet && (
              <p className="text-[10px] text-muted-foreground break-all" style={font}>
                Current: {currentWallet.slice(0, 6)}…{currentWallet.slice(-4)}
              </p>
            )}
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              placeholder="Paste link code…"
              rows={3}
              className="w-full p-2 rounded-md border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 font-mono text-[10px] text-foreground outline-none resize-none break-all"
            />
            {error && <p className="text-[10px] text-red-500 leading-relaxed" style={font}>{error}</p>}
            <button
              onClick={prepare}
              disabled={!code.trim()}
              className="w-full py-2 rounded-md bg-neutral-900 dark:bg-neutral-100 text-white dark:text-black text-xs uppercase tracking-wider hover:opacity-90 transition-opacity disabled:opacity-50"
              style={font}
            >
              Review
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            <p className="text-[11px] text-muted-foreground leading-relaxed" style={font}>
              This will set the wallet below as your agent’s onchain wallet. Anything resolving this
              agent treats it as the agent. Check it against your runtime.
            </p>
            <div className="rounded-md border border-neutral-200 dark:border-neutral-800 p-3 space-y-2">
              <div>
                <p className="text-[9px] uppercase tracking-wider text-muted-foreground" style={font}>Wallet to bind</p>
                <p className="text-[12px] text-foreground break-all select-all" style={font}>{preview.blob.wallet}</p>
              </div>
              <div className="flex items-center justify-between gap-3 pt-1">
                <div><p className="text-[9px] uppercase text-muted-foreground" style={font}>Agent</p><p className="text-[11px] text-foreground" style={font}>#{agentId}</p></div>
                <div><p className="text-[9px] uppercase text-muted-foreground" style={font}>Chain</p><p className="text-[11px] text-foreground" style={font}>{chainName(chainId)}</p></div>
                <div><p className="text-[9px] uppercase text-muted-foreground" style={font}>Expires</p><p className={`text-[11px] ${expired ? 'text-red-500' : 'text-foreground'}`} style={font}>{expired ? 'expired' : `${secondsLeft}s`}</p></div>
              </div>
            </div>

            {preview.sigState === 'ok' ? (
              <p className="flex items-start gap-2 text-[11px] text-green-600 dark:text-green-500" style={font}>
                <Check size={14} className="mt-px shrink-0" /> Signature verified: signed by the wallet shown above.
              </p>
            ) : (
              <div className="space-y-2">
                <p className="flex items-start gap-2 text-[11px] text-amber-600 dark:text-amber-500" style={font}>
                  <AlertTriangle size={14} className="mt-px shrink-0" />
                  Signature could not be verified in-browser (expected for a smart-contract wallet). Only continue if this matches your runtime.
                </p>
                <label className="flex items-start gap-2 text-[11px] text-muted-foreground cursor-pointer" style={font}>
                  <input type="checkbox" checked={acknowledged} onChange={(e) => setAcknowledged(e.target.checked)} className="mt-0.5" />
                  I confirm this is my agent’s wallet address.
                </label>
              </div>
            )}

            {error && <p className="text-[10px] text-red-500 leading-relaxed" style={font}>{error}</p>}

            <div className="flex gap-2">
              <button onClick={() => { setPreview(null); setError(null); }} disabled={status === 'linking'} className="flex-1 py-2 rounded-md border border-neutral-700 dark:border-neutral-200 text-xs uppercase tracking-wider hover:opacity-80 disabled:opacity-50" style={font}>Back</button>
              <button onClick={confirm} disabled={!canConfirm} className="flex-1 py-2 rounded-md bg-neutral-900 dark:bg-neutral-100 text-white dark:text-black text-xs uppercase tracking-wider hover:opacity-90 disabled:opacity-50" style={font}>
                {status === 'linking' ? 'Linking…' : expired ? 'Expired' : 'Confirm & Sign'}
              </button>
            </div>
          </div>
        )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
