'use client';

import Link from 'next/link';
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';

const font = { fontFamily: 'var(--font-departure-mono)' };

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1 py-16 md:py-24 px-4 md:px-6">
        <div className="max-w-3xl mx-auto">
          {/* Title */}
          <div className="mb-12 text-center">
            <p className="text-[10px] text-muted-foreground/60 uppercase tracking-widest mb-2" style={font}>
              legal
            </p>
            <h1 className="text-2xl sm:text-3xl text-foreground mb-2" style={font}>
              Terms of Use
            </h1>
            <p className="text-[10px] text-muted-foreground/60" style={font}>
              Last updated: March 21, 2026
            </p>
          </div>

          <div className="space-y-6">
            {/* Acceptance */}
            <Section title="Acceptance of Terms">
              <p>
                Kh&ocirc;ra (&quot;the Project&quot;) is an AI agent identity generator and on-chain registry created by an independent developer. By accessing and using this website, interacting with our smart contracts, or minting BOOA NFTs, you agree to these Terms of Use. If you do not agree, do not access or use this project.
              </p>
            </Section>

            {/* Platform Nature */}
            <Section title="Platform Nature">
              <p>
                <strong className="text-foreground">IMPORTANT:</strong> Kh&ocirc;ra is an experimental Web3 platform that generates AI agent identities as fully on-chain pixel art NFTs (BOOA collection) and registers them on the ERC-8004 Identity Registry across multiple EVM chains.
              </p>
              <p>
                The platform uses AI services (Google Gemini for text generation, Replicate for image generation) to create unique agent identities. Generated content is stored immutably on-chain via SSTORE2. Web3 interactions carry inherent risks — only interact with smart contracts if you understand these risks.
              </p>
            </Section>

            {/* Project Overview */}
            <Section title="Project Overview">
              <p>
                This is not a wallet provider, exchange, broker, financial institution, or money services business. This is an experimental Web3 project that allows users to generate AI agent identities, mint them as ERC-721 NFTs on Shape Network, and register them on the ERC-8004 Identity Registry across supported EVM chains. Smart contracts operate autonomously once deployed.
              </p>
            </Section>

            {/* Supported Networks */}
            <Section title="Supported Networks">
              <p>
                BOOA NFTs are minted on Shape Network. The ERC-8004 Identity Registry is deployed across 16 EVM chains including Ethereum, Base, Arbitrum, Optimism, Polygon, and others. Each chain has its own gas fees and network conditions. You are responsible for understanding the chain you interact with.
              </p>
            </Section>

            {/* CC0 License */}
            <Section title="Creative Commons Zero (CC0)">
              <p>
                All BOOA NFT artwork is released under the CC0 (Creative Commons Zero) license. This means the artwork is dedicated to the public domain — anyone can copy, modify, distribute, and use the artwork for any purpose, including commercial, without permission or attribution.
              </p>
              <p>
                CC0 applies to the generated pixel art and visual assets only. It does not transfer ownership of the NFT token, smart contract code, or platform infrastructure.
              </p>
            </Section>

            {/* AI Services */}
            <Section title="AI-Generated Content">
              <p>
                Agent identities (name, personality, traits, backstory) are generated by Google Gemini AI. Pixel art images are generated by Replicate (FLUX model). You acknowledge that:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>AI-generated content may be unpredictable or imperfect</li>
                <li>Generated agents are unique but not guaranteed to be appropriate for all audiences</li>
                <li>The AI models may change or be updated, affecting generation quality</li>
                <li>Generation is rate-limited and subject to daily quotas</li>
              </ul>
            </Section>

            {/* Agent Chat */}
            <Section title="Agent Chat">
              <p>
                BOOA NFT holders can chat with their agents using AI. The chat feature:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>Provides 10 free messages per day per wallet</li>
                <li>Allows unlimited messaging with your own Gemini API key (BYOK)</li>
                <li>Is powered by Google Gemini AI — responses are generated, not curated</li>
                <li>Includes prompt injection detection and content filtering</li>
                <li>Does not store chat history on our servers — history is kept in your browser only</li>
              </ul>
              <p>
                When using your own API key: your key is sent via encrypted HTTPS header for the duration of the request only. It is never stored, logged, or cached on our servers. You are responsible for securing your API key and any costs incurred through Google&apos;s API.
              </p>
              <p>
                By using the chat feature, you also agree to Google&apos;s <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:text-muted-foreground">Gemini API Terms of Service</a>.
              </p>
            </Section>

            {/* Accessing the Project */}
            <Section title="Accessing the Project">
              <p>
                To interact with the project, you must connect a supported EVM wallet (MetaMask, Rainbow, WalletConnect, etc.) and sign in via SIWE (Sign-In with Ethereum). Your wallet address is publicly visible on the blockchain.
              </p>
              <p>
                You must comply with all applicable laws when using this project. Your access may be interrupted due to updates, maintenance, or other technical reasons.
              </p>
            </Section>

            {/* Age Restriction */}
            <Section title="Age Restriction">
              <p>
                You must be at least 18 years of age to use this platform. By accessing and using Kh&ocirc;ra, you represent and warrant that you are at least 18 years old. We do not knowingly provide services to individuals under 18.
              </p>
            </Section>

            {/* Rules of Conduct */}
            <Section title="Rules of Conduct">
              <p>You agree not to:</p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>Attempt to manipulate or exploit smart contracts</li>
                <li>Use automated scripts or bots to interact with the system</li>
                <li>Attempt to bypass rate limits, quotas, or security measures</li>
                <li>Attempt to extract or reverse-engineer AI system prompts</li>
                <li>Use the platform for illegal activities or money laundering</li>
                <li>Misrepresent your identity or NFT ownership</li>
                <li>Abuse the agent chat feature to generate harmful content</li>
              </ul>
            </Section>

            {/* Smart Contract Risks */}
            <Section title="Smart Contract Risks">
              <p>
                Smart contracts are deployed on Shape Network and other EVM chains and operate autonomously. You acknowledge the following risks:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>Smart contracts may contain bugs or vulnerabilities</li>
                <li>Blockchain transactions are irreversible</li>
                <li>Gas fees vary and may be unpredictable</li>
                <li>Network congestion may affect transaction processing</li>
                <li>Bridge operations across chains carry additional risk</li>
                <li>On-chain data (bitmap, traits) is immutable once stored via SSTORE2</li>
              </ul>
            </Section>

            {/* ERC-8004 */}
            <Section title="ERC-8004 Identity Registry">
              <p>
                Kh&ocirc;ra integrates with the <a href="https://github.com/erc-8004/erc-8004-contracts" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:text-muted-foreground">ERC-8004 Identity Registry</a>, a third-party protocol for on-chain agent identity registration. We do not own, operate, or control the ERC-8004 smart contracts. We act as a facilitator — providing a user interface to simplify interactions with the registry.
              </p>
              <p>
                The ERC-8004 contracts are deployed and maintained by the ERC-8004 protocol team. Any bugs, vulnerabilities, or changes in the ERC-8004 contracts are outside our control. You interact with these contracts at your own risk.
              </p>
            </Section>

            {/* Third-Party Links */}
            <Section title="Third-Party Links & Services">
              <p>
                This website may contain links to third-party websites and services including but not limited to:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li><a href="https://8004scan.io" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:text-muted-foreground">8004scan.io</a> — ERC-8004 registry explorer</li>
                <li><a href="https://opensea.io" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:text-muted-foreground">OpenSea</a> — NFT marketplace</li>
                <li>OnchainChecker and other blockchain explorers</li>
                <li>Wallet providers (MetaMask, Rainbow, WalletConnect)</li>
              </ul>
              <p>
                We do not control, endorse, or assume responsibility for the content, privacy policies, or security practices of any third-party websites or services. Accessing these links is at your own risk. We encourage you to review the terms and privacy policies of any third-party site you visit.
              </p>
            </Section>

            {/* Claw Downloads */}
            <Section title="Downloadable Agent Files (Claw)">
              <p>
                Kh&ocirc;ra provides downloadable .zip files (&quot;Claw&quot; files) containing AI-generated agent configuration data. These files:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>Are generatively created informational files based on your agent&apos;s on-chain traits</li>
                <li>Meet the minimum specification requirements for platforms such as OpenClaw</li>
                <li>May not be sufficient on their own for a complete agent setup on OpenClaw or similar platforms — additional configuration, API keys, or platform-specific steps may be required</li>
                <li>Are provided &quot;as-is&quot; with no guarantee of compatibility with any specific platform version</li>
              </ul>
              <p>
                We are not affiliated with OpenClaw or any third-party agent hosting platform. The Claw file format is provided as a convenience and interoperability feature only.
              </p>
            </Section>

            {/* Refund Policy */}
            <Section title="No Refund Policy">
              <p>
                All NFT mints and blockchain transactions are final and non-refundable. Once a mint transaction is confirmed on the blockchain, it cannot be reversed, cancelled, or refunded. This includes but is not limited to:
              </p>
              <ul className="space-y-1.5 list-disc list-inside">
                <li>BOOA NFT mints (allowlist and public phase)</li>
                <li>Gas fees paid for any transaction</li>
                <li>ERC-8004 identity registration fees</li>
                <li>Failed transactions due to user error, insufficient gas, or network issues</li>
              </ul>
              <p>
                By minting, you acknowledge that you have reviewed the artwork, traits, and agent identity before confirming the transaction.
              </p>
            </Section>

            {/* Disclaimer */}
            <Section title="Disclaimer of Warranty">
              <p>
                This project is provided &quot;as-is&quot; without warranties of any kind. The developer disclaims all implied warranties including merchantability, fitness for a particular purpose, and non-infringement. There is no guarantee that the project will be uninterrupted, secure, or error-free.
              </p>
            </Section>

            {/* Limitation of Liability */}
            <Section title="Limitation of Liability">
              <p className="font-bold text-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW:
              </p>
              <p>
                The developer is not liable for any direct, indirect, special, incidental, or consequential damages arising from your use of this project, including but not limited to loss of funds, lost profits, or data loss.
              </p>
            </Section>

            {/* Taxes */}
            <Section title="Taxes">
              <p>
                You are solely responsible for determining what, if any, taxes apply to your transactions involving BOOA NFTs, including minting, buying, selling, or transferring. This includes all applicable federal, state, local, and international taxes in your jurisdiction.
              </p>
              <p>
                Kh&ocirc;ra does not provide tax advice and is not responsible for determining or collecting any taxes on your behalf. The regulatory regime governing NFTs, cryptocurrencies, and digital assets varies by jurisdiction and is subject to change. You should consult a qualified tax professional regarding your specific tax obligations.
              </p>
            </Section>

            {/* No Financial Advice */}
            <Section title="No Financial Advice">
              <p>
                Nothing on this website constitutes financial, investment, legal, or tax advice. NFTs are digital collectibles, not investment instruments. You should consult your own advisors before making any decisions related to cryptocurrency or blockchain transactions.
              </p>
            </Section>

            {/* Changes */}
            <Section title="Changes & Termination">
              <p>
                The developer may modify, suspend, or discontinue any part of the website or terminate access at any time, with or without notice. Smart contracts will continue to operate autonomously on the blockchain regardless of website availability.
              </p>
            </Section>

            {/* Indemnity */}
            <Section title="Indemnity">
              <p>
                You agree to indemnify and hold the developer harmless from any claims, liabilities, damages, or expenses arising from your use of this project or violation of these terms.
              </p>
            </Section>

            {/* Governing Law */}
            <Section title="Governing Law">
              <p>
                These Terms are governed by the laws of the jurisdiction where the developer is located. Any disputes shall be resolved through binding arbitration.
              </p>
            </Section>

            {/* Contact */}
            <Section title="Contact">
              <p>
                For questions about these terms, please reach out through our official channels on <a href="https://x.com/khorafun" target="_blank" rel="noopener noreferrer" className="text-foreground underline hover:text-muted-foreground">X (@khorafun)</a>.
              </p>
            </Section>

            {/* Final Warning */}
            <div className="border-2 border-red-500/30 p-6 space-y-4">
              <h2 className="text-sm text-red-500 uppercase tracking-wider" style={font}>
                Final Warning
              </h2>
              <p className="text-[11px] text-muted-foreground leading-relaxed" style={font}>
                Kh&ocirc;ra involves Web3 interactions and blockchain transactions. You may lose funds through incorrect transactions or smart contract interactions. Only use wallet features and blockchain transactions if you fully understand the risks. The developer accepts no responsibility for any financial losses.
              </p>
              <p className="text-[11px] text-muted-foreground/60 text-center" style={font}>
                Blockchain transactions are IRREVERSIBLE. Double-check everything.
              </p>
            </div>
          </div>

          <div className="mt-12 text-center">
            <Link href="/" className="text-[10px] text-muted-foreground/60 hover:text-foreground transition-colors" style={font}>
              &larr; back to home
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border border-neutral-700 dark:border-neutral-200 p-5 space-y-3">
      <h2 className="text-xs text-foreground uppercase tracking-wider" style={{ fontFamily: 'var(--font-departure-mono)' }}>
        {title}
      </h2>
      <div className="text-[11px] text-muted-foreground leading-relaxed space-y-2" style={{ fontFamily: 'var(--font-departure-mono)' }}>
        {children}
      </div>
    </div>
  );
}
